# extensions for tilt
load('ext://secret', 'secret_yaml_tls')

# deploy cert manager
load('cert_manager_windows.tilt', 'deploy_cert_manager')
deploy_cert_manager()

# deploy cluster issuer
k8s_yaml(secret_yaml_tls(name='root-ca', namespace='cert-manager', cert='../0_certs/root-ca/root-ca.pem', key='../0_certs/root-ca/root-ca-key.pem'))
k8s_yaml('clusterissuer.yaml')

# deploy namespaces
k8s_yaml('namespaces.yaml')

# deploy the platform
k8s_yaml(local('kustomize build . --enable-helm'))

# label resources and forward traffic to istio
k8s_resource('istiod', labels="istio")
k8s_resource('istio-gateway', port_forwards=['443:443', '80:80'], labels="istio")

# postgres
k8s_resource('pg', port_forwards=5432, labels="postgres")
k8s_resource('create-keycloak-db', labels="postgres")

# keycloak 
k8s_resource('kc', labels="keycloak")

# oauth2 proxy
k8s_resource('oauth2-proxy', labels="oauth2-proxy")
k8s_resource('oauth2-proxy-redis-master', labels="oauth2-proxy")
k8s_resource('create-client-oauth2proxy', labels="oauth2-proxy")

# argocd
k8s_resource('argocd-server', labels="argocd")
k8s_resource('argocd-repo-server', labels="argocd")
k8s_resource('argocd-redis', labels="argocd")
k8s_resource('argocd-application-controller', labels="argocd")
k8s_resource('argocd-applicationset-controller', labels="argocd")
k8s_resource('argocd-notifications-controller', labels="argocd")
k8s_resource('create-client-argocd', labels="argocd")